### ISSUE TITLE
Open question commaai body 

### ISSUE THREAD

**Issue by EFeru** [commaai/body#4]
Hi @briskspirit @geohot ,

It's amazing what you did with the commaai body and happy to see you are using my FOC core.
If you need any support/changes on the FOC core or maybe building a simulator, let me know.

I made a simulator some time back, before adding any balancing control în MATLAB/Simulink Multibody.

All the best,
Emanuel

No control, falls like a brick (later I added some controls but didn't make a movie).
https://user-images.githubusercontent.com/24780745/175463233-3821926c-3b70-41f8-a61e-c8fcc5565d9c.mp4

**Comment by briskspirit** [comment]
@EFeru I like your idea with simulator and we would definitely appreciate having one. Soon we will add 2 more axes to the body so simulator will definitely help to figure out control algorithm. How I can contact you?

**Comment by EFeru** [comment]
Cool. Good to hear. You can contact me by email e.feru01@gmail.com and we take it up from there.
